# By beamyyl, with blur
# --- Backend ---
backend = "glx";
vsync = true;

# --- Fading ---
fading = true;
fade-delta = 5;
fade-in-step = 0.03;
fade-out-step = 0.03;

# --- Transparency ---
inactive-opacity = 0.90;
active-opacity = 1.0;
frame-opacity = 1.0;
detect-client-opacity = true;

# --- Blur ---
blur-method = "dual_kawase"; 
blur-strength = 3; 
blur-background = true;

# --- Shadows ---
shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.35;

# --- General ---
use-damage = true;

# Exclusions
blur-background-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'slop'"
];

shadow-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'slop'"
];
